png(filename="plot3.png", width=480, height=480)
plot(x=hpc$dt, y=hpc$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(x=hpc$dt, y=hpc$Sub_metering_2, col="red")
lines(x=hpc$dt, y=hpc$Sub_metering_3, col="blue")
legend("topright", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1))
dev.off()